# import_currency_symbols.py
"""
Module to import and manage currency symbols for different countries
"""

import json, os

filename = "currencies.json"

default_currencies = {
    "Afghanistan": {"currency_code": "AFN", "symbol": "؋"},
    "Albania": {"currency_code": "ALL", "symbol": "L"},
    "Algeria": {"currency_code": "DZD", "symbol": "دج"},
    "Andorra": {"currency_code": "EUR", "symbol": "€"},
    "Angola": {"currency_code": "AOA", "symbol": "Kz"},
    "Antigua and Barbuda": {"currency_code": "XCD", "symbol": "$"},
    "Argentina": {"currency_code": "ARS", "symbol": "$"},
    "Armenia": {"currency_code": "AMD", "symbol": "֏"},
    "Australia": {"currency_code": "AUD", "symbol": "$"},
    "Austria": {"currency_code": "EUR", "symbol": "€"},
    "Azerbaijan": {"currency_code": "AZN", "symbol": "₼"},
    "Bahamas": {"currency_code": "BSD", "symbol": "$"},
    "Bahrain": {"currency_code": "BHD", "symbol": ".د.ب"},
    "Bangladesh": {"currency_code": "BDT", "symbol": "৳"},
    "Barbados": {"currency_code": "BBD", "symbol": "$"},
    "Belarus": {"currency_code": "BYN", "symbol": "Br"},
    "Belgium": {"currency_code": "EUR", "symbol": "€"},
    "Belize": {"currency_code": "BZD", "symbol": "BZ$"},
    "Benin": {"currency_code": "XOF", "symbol": "CFA"},
    "Bhutan": {"currency_code": "BTN", "symbol": "Nu."},
    "Bolivia": {"currency_code": "BOB", "symbol": "Bs."},
    "Bosnia and Herzegovina": {"currency_code": "BAM", "symbol": "КМ"},
    "Botswana": {"currency_code": "BWP", "symbol": "P"},
    "Brazil": {"currency_code": "BRL", "symbol": "R$"},
    "Brunei": {"currency_code": "BND", "symbol": "$"},
    "Bulgaria": {"currency_code": "BGN", "symbol": "лв"},
    "Burkina Faso": {"currency_code": "XOF", "symbol": "CFA"},
    "Burundi": {"currency_code": "BIF", "symbol": "FBu"},
    "Cambodia": {"currency_code": "KHR", "symbol": "៛"},
    "Cameroon": {"currency_code": "XAF", "symbol": "FCFA"},
    "Canada": {"currency_code": "CAD", "symbol": "$"},
    "Cape Verde": {"currency_code": "CVE", "symbol": "$"},
    "Central African Republic": {"currency_code": "XAF", "symbol": "FCFA"},
    "Chad": {"currency_code": "XAF", "symbol": "FCFA"},
    "Chile": {"currency_code": "CLP", "symbol": "$"},
    "China": {"currency_code": "CNY", "symbol": "¥ / 元"},
    "Colombia": {"currency_code": "COP", "symbol": "$"},
    "Comoros": {"currency_code": "KMF", "symbol": "CF"},
    "Congo, Republic of the": {"currency_code": "XAF", "symbol": "FCFA"},
    "Congo, Democratic Republic of": {"currency_code": "CDF", "symbol": "FC"},
    "Costa Rica": {"currency_code": "CRC", "symbol": "₡"},
    "Côte d'Ivoire": {"currency_code": "XOF", "symbol": "CFA"},
    "Croatia": {"currency_code": "EUR", "symbol": "€"},
    "Cuba": {"currency_code": "CUP", "symbol": "$"},
    "Cyprus": {"currency_code": "EUR", "symbol": "€"},
    "Czech Republic": {"currency_code": "CZK", "symbol": "Kč"},
    "Denmark": {"currency_code": "DKK", "symbol": "kr"},
    "Djibouti": {"currency_code": "DJF", "symbol": "Fdj"},
    "Dominica": {"currency_code": "XCD", "symbol": "$"},
    "Dominican Republic": {"currency_code": "DOP", "symbol": "RD$"},
    "Ecuador": {"currency_code": "USD", "symbol": "$"},
    "Egypt": {"currency_code": "EGP", "symbol": "£ / ج.م"},
    "El Salvador": {"currency_code": "USD", "symbol": "$"},
    "Equatorial Guinea": {"currency_code": "XAF", "symbol": "FCFA"},
    "Eritrea": {"currency_code": "ERN", "symbol": "Nfk"},
    "Estonia": {"currency_code": "EUR", "symbol": "€"},
    "Eswatini (Swaziland)": {"currency_code": "SZL", "symbol": "E"},
    "Ethiopia": {"currency_code": "ETB", "symbol": "Br"},
    "Fiji": {"currency_code": "FJD", "symbol": "$"},
    "Finland": {"currency_code": "EUR", "symbol": "€"},
    "France": {"currency_code": "EUR", "symbol": "€"},
    "Gabon": {"currency_code": "XAF", "symbol": "FCFA"},
    "Gambia": {"currency_code": "GMD", "symbol": "D"},
    "Georgia": {"currency_code": "GEL", "symbol": "₾"},
    "Germany": {"currency_code": "EUR", "symbol": "€"},
    "Ghana": {"currency_code": "GHS", "symbol": "₵"},
    "Greece": {"currency_code": "EUR", "symbol": "€"},
    "Grenada": {"currency_code": "XCD", "symbol": "$"},
    "Guatemala": {"currency_code": "GTQ", "symbol": "Q"},
    "Guinea": {"currency_code": "GNF", "symbol": "FG"},
    "Guinea-Bissau": {"currency_code": "XOF", "symbol": "CFA"},
    "Guyana": {"currency_code": "GYD", "symbol": "$"},
    "Haiti": {"currency_code": "HTG", "symbol": "G"},
    "Honduras": {"currency_code": "HNL", "symbol": "L"},
    "Hungary": {"currency_code": "HUF", "symbol": "Ft"},
    "Iceland": {"currency_code": "ISK", "symbol": "kr"},
    "India": {"currency_code": "INR", "symbol": "₹"},
    "Indonesia": {"currency_code": "IDR", "symbol": "Rp"},
    "Iran": {"currency_code": "IRR", "symbol": "﷼"},
    "Iraq": {"currency_code": "IQD", "symbol": "ع.د"},
    "Ireland": {"currency_code": "EUR", "symbol": "€"},
    "Israel": {"currency_code": "ILS", "symbol": "₪"},
    "Italy": {"currency_code": "EUR", "symbol": "€"},
    "Jamaica": {"currency_code": "JMD", "symbol": "J$"},
    "Japan": {"currency_code": "JPY", "symbol": "¥"},
    "Jordan": {"currency_code": "JOD", "symbol": "د.ا"},
    "Kazakhstan": {"currency_code": "KZT", "symbol": "₸"},
    "Kenya": {"currency_code": "KES", "symbol": "KSh"},
    "Kiribati": {"currency_code": "AUD", "symbol": "$"},
    "Korea, North": {"currency_code": "KPW", "symbol": "₩"},
    "Korea, South": {"currency_code": "KRW", "symbol": "₩"},
    "Kuwait": {"currency_code": "KWD", "symbol": "د.ك"},
    "Kyrgyzstan": {"currency_code": "KGS", "symbol": "с"},
    "Laos": {"currency_code": "LAK", "symbol": "₭"},
    "Latvia": {"currency_code": "EUR", "symbol": "€"},
    "Lebanon": {"currency_code": "LBP", "symbol": "ل.ل"},
    "Lesotho": {"currency_code": "LSL", "symbol": "M"},
    "Liberia": {"currency_code": "LRD", "symbol": "$"},
    "Libya": {"currency_code": "LYD", "symbol": "ل.د"},
    "Liechtenstein": {"currency_code": "CHF", "symbol": "CHF / Fr."},
    "Lithuania": {"currency_code": "EUR", "symbol": "€"},
    "Luxembourg": {"currency_code": "EUR", "symbol": "€"},
    "Madagascar": {"currency_code": "MGA", "symbol": "Ar"},
    "Malawi": {"currency_code": "MWK", "symbol": "MK"},
    "Malaysia": {"currency_code": "MYR", "symbol": "RM"},
    "Maldives": {"currency_code": "MVR", "symbol": "ރ."},
    "Mali": {"currency_code": "XOF", "symbol": "CFA"},
    "Malta": {"currency_code": "EUR", "symbol": "€"},
    "Marshall Islands": {"currency_code": "USD", "symbol": "$"},
    "Mauritania": {"currency_code": "MRU", "symbol": "UM"},
    "Mauritius": {"currency_code": "MUR", "symbol": "₨"},
    "Mexico": {"currency_code": "MXN", "symbol": "$"},
    "Micronesia": {"currency_code": "USD", "symbol": "$"},
    "Moldova": {"currency_code": "MDL", "symbol": "L"},
    "Monaco": {"currency_code": "EUR", "symbol": "€"},
    "Mongolia": {"currency_code": "MNT", "symbol": "₮"},
    "Montenegro": {"currency_code": "EUR", "symbol": "€"},
    "Morocco": {"currency_code": "MAD", "symbol": "د.م."},
    "Mozambique": {"currency_code": "MZN", "symbol": "MT"},
    "Myanmar": {"currency_code": "MMK", "symbol": "K"},
    "Namibia": {"currency_code": "NAD", "symbol": "$"},
    "Nauru": {"currency_code": "AUD", "symbol": "$"},
    "Nepal": {"currency_code": "NPR", "symbol": "₨"},
    "Netherlands": {"currency_code": "EUR", "symbol": "€"},
    "New Zealand": {"currency_code": "NZD", "symbol": "$"},
    "Nicaragua": {"currency_code": "NIO", "symbol": "C$"},
    "Niger": {"currency_code": "XOF", "symbol": "CFA"},
    "Nigeria": {"currency_code": "NGN", "symbol": "₦"},
    "North Macedonia": {"currency_code": "MKD", "symbol": "ден"},
    "Norway": {"currency_code": "NOK", "symbol": "kr"},
    "Oman": {"currency_code": "OMR", "symbol": "ر.ع."},
    "Pakistan": {"currency_code": "PKR", "symbol": "₨"},
    "Palau": {"currency_code": "USD", "symbol": "$"},
    "Panama": {"currency_code": "PAB / USD", "symbol": "B/. / $"},
    "Papua New Guinea": {"currency_code": "PGK", "symbol": "K"},
    "Paraguay": {"currency_code": "PYG", "symbol": "₲"},
    "Peru": {"currency_code": "PEN", "symbol": "S/."},
    "Philippines": {"currency_code": "PHP", "symbol": "₱"},
    "Poland": {"currency_code": "PLN", "symbol": "zł"},
    "Portugal": {"currency_code": "EUR", "symbol": "€"},
    "Qatar": {"currency_code": "QAR", "symbol": "ر.ق"},
    "Romania": {"currency_code": "RON", "symbol": "lei"},
    "Russia": {"currency_code": "RUB", "symbol": "₽"},
    "Rwanda": {"currency_code": "RWF", "symbol": "RF"},
    "Saint Kitts and Nevis": {"currency_code": "XCD", "symbol": "$"},
    "Saint Lucia": {"currency_code": "XCD", "symbol": "$"},
    "Saint Vincent and the Grenadines": {"currency_code": "XCD", "symbol": "$"},
    "Samoa": {"currency_code": "WST", "symbol": "T"},
    "San Marino": {"currency_code": "EUR", "symbol": "€"},
    "Sao Tome and Principe": {"currency_code": "STN", "symbol": "Db"},
    "Saudi Arabia": {"currency_code": "SAR", "symbol": "﷼"},
    "Senegal": {"currency_code": "XOF", "symbol": "CFA"},
    "Serbia": {"currency_code": "RSD", "symbol": "дин."},
    "Seychelles": {"currency_code": "SCR", "symbol": "₨"},
    "Sierra Leone": {"currency_code": "SLL", "symbol": "Le"},
    "Singapore": {"currency_code": "SGD", "symbol": "$"},
    "Slovakia": {"currency_code": "EUR", "symbol": "€"},
    "Slovenia": {"currency_code": "EUR", "symbol": "€"},
    "Solomon Islands": {"currency_code": "SBD", "symbol": "$"},
    "Somalia": {"currency_code": "SOS", "symbol": "Sh"},
    "South Africa": {"currency_code": "ZAR", "symbol": "R"},
    "South Sudan": {"currency_code": "SSP", "symbol": "£"},
    "Spain": {"currency_code": "EUR", "symbol": "€"},
    "Sri Lanka": {"currency_code": "LKR", "symbol": "Rs"},
    "Sudan": {"currency_code": "SDG", "symbol": "£"},
    "Suriname": {"currency_code": "SRD", "symbol": "$"},
    "Sweden": {"currency_code": "SEK", "symbol": "kr"},
    "Switzerland": {"currency_code": "CHF", "symbol": "CHF / Fr."},
    "Syria": {"currency_code": "SYP", "symbol": "£"},
    "Taiwan": {"currency_code": "TWD", "symbol": "NT$"},
    "Tajikistan": {"currency_code": "TJS", "symbol": "ЅМ"},
    "Tanzania": {"currency_code": "TZS", "symbol": "TSh"},
    "Thailand": {"currency_code": "THB", "symbol": "฿"},
    "Togo": {"currency_code": "XOF", "symbol": "CFA"},
    "Tonga": {"currency_code": "TOP", "symbol": "T$"},
    "Trinidad and Tobago": {"currency_code": "TTD", "symbol": "$"},
    "Tunisia": {"currency_code": "TND", "symbol": "د.ت"},
    "Turkey": {"currency_code": "TRY", "symbol": "₺"},
    "Turkmenistan": {"currency_code": "TMT", "symbol": "m"},
    "Tuvalu": {"currency_code": "AUD", "symbol": "$"},
    "Uganda": {"currency_code": "UGX", "symbol": "USh"},
    "Ukraine": {"currency_code": "UAH", "symbol": "₴"},
    "United Arab Emirates": {"currency_code": "AED", "symbol": "د.إ"},
    "United Kingdom": {"currency_code": "GBP", "symbol": "£"},
    "United States of America": {"currency_code": "USD", "symbol": "$"},
    "Uruguay": {"currency_code": "UYU", "symbol": "$U"},
    "Uzbekistan": {"currency_code": "UZS", "symbol": "so'm"},
    "Vanuatu": {"currency_code": "VUV", "symbol": "VT"},
    "Vatican City": {"currency_code": "EUR", "symbol": "€"},
    "Venezuela": {"currency_code": "VES", "symbol": "Bs."},
    "Vietnam": {"currency_code": "VND", "symbol": "₫"},
    "Yemen": {"currency_code": "YER", "symbol": "﷼"},
    "Zambia": {"currency_code": "ZMW", "symbol": "ZK"},
    "Zimbabwe": {"currency_code": "ZWL (plus USD)", "symbol": "Z$"}
}

# Create the currencies.json file if it doesn't exist
if not os.path.exists(filename):
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(default_currencies, f, ensure_ascii=False, indent=2)
    print(f"File {filename} limeundwa.")
else:
    print(f"File {filename} tayari lipo.")

with open(filename, "r", encoding="utf-8") as f:
    currencies = json.load(f)

# Function to get currency symbol by country name
def get_currency_symbol(country_name):
    """Retrieve currency symbol by country name or currency code."""
    for country, data in currencies.items():
        if country.lower() == country_name.lower():
            return data['symbol'], data['currency_code']
    return None